### ISSUE TITLE
Статья

### ISSUE THREAD

**Issue by makleso6** [hhru/AnalyticsGen#31]
Привет! Случайно наткнулся на либку) 
Будет ли пост касательно использования?

**Comment by timbaev** [comment]
Привет! Классно, что есть какой-то сторонний интерес 🔥 
Сейчас мы в процессе обкатки этого решения и хочется его сделать более универсальным, чтобы можно было использовать с любым проектом.
Возможно, накидаем статью с промежуточными результатами 👀
